version: '3'
services:
  postgres:
    image: postgres:10.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: userapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
    volumes:
      - ./postgres-data-userapi:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql